swagger: '2.0'
info:
  version: '1.0.0'
  title: API Gateway
  x-ibm-name: api-gateway
  contact:
    name: API Support
    url: https://example.com/support
    email: support@example.com
basePath: /
x-ibm-configuration:
  properties:
    target-url:
      value: https://jsonplaceholder.typicode.com
      description: Target URL for the API
      encoded: false
  cors:
    enabled: true
  gateway: datapower-api-gateway
  type: rest
  phase: realized
  enforced: true
  testable: true
  assembly:
    execute:
      - invoke:
          title: Invoke
          version: 2.0.0
          verb: keep
          target-url: $(target-url)$(request.path)$(request.search)
          follow-redirects: false
          timeout: 60
          parameter-control:
            type: allowlist
            values: []
          header-control:
            type: blocklist
            values: []
          inject-proxy-headers: true
          persistent-connection: true
      - log:
          version: 2.1.0
          title: Log
          log-level: default
          mode: gather-only
      - set-variable:
          version: 2.0.0
          title: Set Variable
          actions:
            - set: log.custom_data.discoveryServiceCollection
              value: 'true'
              type: string
          description: Setting specific collector key
      - set-variable:
          version: 2.0.0
          title: Set Variable
          actions:
            - set: log.custom_data.apiTargetURL
              value: $(target-url)
              type: string
          description: Setting specific collector target URL
    catch: []
    finally: []
  activity-log:
    enabled: true
    success-content: payload
    error-content: payload
  catalogs: {}
  buffering: true
paths:
  /{+pathparam}:
    get:
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      consumes: []
      produces: []
    post:
      responses:
        '201':
          description: Created
          schema:
            type: string
      consumes: []
      produces: []
    put:
      responses:
        '201':
          description: Created
          schema:
            type: string
    patch:
      responses:
        '200':
          description: Successful response
          schema:
            type: string
      consumes: []
      produces: []
    delete:
      responses:
        '204':
          description: No content
          schema:
            type: string
      consumes: []
      produces: []
    parameters:
      - name: pathparam
        in: path
        required: true
        type: string
schemes:
  - https